spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    driver-class-name: org.postgresql.Driver
    username: test
    password: 'test'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create